### ISSUE TITLE
[Bounty Complete] Get contract source code

### ISSUE THREAD

**Issue by whoabuddy** [aibtcdev/agent-tools-ts#11]
## AIBTCdev Bounty

A tool that allows an agent to get the source code for a given contract's fully-qualified name.

### Prize

$250 in BTC

#### Functionality

1. ability to get the source code for a provided contract name

#### Development

- tools should be submitted as a PR to this repository, ideally in its own folder
- each tool uses Stacks.js libraries or Hiro APIs to access wallet / blockchain
- each tool must perform a single action and return output the LLM can use
- each tool can accept an optional parameter that is passed to the script
- each tool should catch, describe, and relay all known errors for the LLM to revise

**Comment by Emmanueltech** [comment]
Hi, I would like to work on this
