### ISSUE TITLE
[Bounty Complete] Add tools for native STX

### ISSUE THREAD

**Issue by whoabuddy** [aibtcdev/agent-tools-ts#12]
## AIBTCdev Bounty

Add abilities to interact with native STX.

### Prize

$750 in BTC

### Tool Criteria

A finalized PR would include 2 scripts that follow the criteria listed below and work independently using `bun run`.

#### Functionality

1. ability to get the locked, unlocked, and total STX balance for a given address
2. ability to create and submit a STX transfer transaction

#### Development

- tools should be submitted as a PR to this repository, ideally in its own folder
- each tool uses Stacks.js libraries or Hiro APIs to access wallet / blockchain
- each tool must perform a single action and return output the LLM can use
- each tool can accept an optional parameter that is passed to the script
- each tool should catch, describe, and relay all known errors for the LLM to revise

**Comment by ManyRios** [comment]
Hi! I would like to help with this, there is a contribution guide or something?

**Comment by whoabuddy** [comment]
@ManyRios thanks for the interest! By the time that comment came in there were already two submissions, these can go fast!

Completed first by @hashhavoccat 
- #19 

Shout-out for completing as well to @rapha-btc a few hours later
- #21
