### ISSUE TITLE
[Bounty Complete] Add tools for stacking STX

### ISSUE THREAD

**Issue by whoabuddy** [aibtcdev/agent-tools-ts#13]
## AIBTCdev Bounty

Add tools for stacking STX in a pool, similar to what lockstacks.com offers users in UI form.

### Prize

$1,000 in BTC

#### Functionality

- ability to perform all related stacking functions for a pool:
  - mapping of pools to contracts (can we get this from an API?)
  - allowing the correct contract caller
  - locking and stacking STX
  - revoking stacking STX (and optionally locking again)
- ability to perform liquid stacking functions:
  - basic deposit and withdraw to start

#### Development

- tools should be submitted as a PR to this repository, ideally in its own folder
- each tool uses Stacks.js libraries or Hiro APIs to access wallet / blockchain
- each tool must perform a single action and return output the LLM can use
- each tool can accept an optional parameter that is passed to the script
- each tool should catch, describe, and relay all known errors for the LLM to revise

**Comment by Emmanueltech** [comment]
Hi, I have worked on stacking before and would like to get the full requirements for this task.

**Comment by whoabuddy** [comment]
Hey @Emmanueltech everything was just updated and will be announced as the next live bounty in the upcoming meeting :)

**Comment by whoabuddy** [comment]
Hey @shaik-sirajuddin thank you for the PRs! On first glance it looks to implement all functionality so closing this as a completed bounty for now. I'll provide specific feedback in the PR and we'll get everything settled from there, as well as resolve that little syntax issue. What's the best way to reach you outside of GitHub?
- #25

**Comment by Shaik-Sirajuddin** [comment]
> Hey @Shaik-Sirajuddin thank you for the PRs! On first glance it looks to implement all functionality so closing this as a completed bounty for now. I'll provide specific feedback in the PR and we'll get everything settled from there, as well as resolve that little syntax issue. What's the best way to reach you outside of GitHub?
> 
>     * [feat: stacking tools for pool , liquid stacking #25](https://github.com/aibtcdev/agent-tools-ts/pull/25)

Looking forward to your feedback
You can reach me at [twitter](https://x.com/sirajuddin__sk)
